[tool.poetry]
name = "vq-ama-agent"
version = "0.1.0"
# package-mode = false

packages = [
  { include = "*", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.0"
langchain = "^0.3.25"
faiss-cpu = "^1.7.2"
PyYAML = "^6.0"
python-dotenv = "^1.0.0"
typer = "^0.9.0"
boto3 = "^1.28.0"
langchain-community = "^0.3.25"
chromadb = "^1.0.12"
langchain-aws =  "^0.2.25"
langchain-chroma = "^0.2.4"
pypdf = "^5.6.0"
unstructured = "0.18.11"
"pdfminer.six" = "^20250506"
pi-heif = "^1.0.0"
unstructured-inference = "^1.0.5"
pdf2image = "^1.17.0"
poppler-utils = "^0.1.0"
flask = "^3.1.1"
flask-cors = "^6.0.1"

[tool.poetry.scripts]
vq-ama-agent = "src.main:cli"
